run .............F
Failures:

  1) GridPointSet #connected? when (x-1,y) pattern should return true
     Failure/Error: expect(grid_point_set.connected?).to eq true

     NoMethodError:
       undefined method `connected?' for #<GridPointSet:0x0000000104b2b510 @grid_points=[#<GridPoint:0x0000000104b2b600 @x=1, @y=2>, #<GridPoint:0x0000000104b2b538 @x=0, @y=2>]>

               expect(grid_point_set.connected?).to eq true
                                    ^^^^^^^^^^^
       Did you mean?  connected
     # ./spec/main_spec.rb:84:in `block (4 levels) in <top (required)>'

Finished in 0.00225 seconds (files took 0.04558 seconds to load)
14 examples, 1 failure

Failed examples:

rspec ./spec/main_spec.rb:83 # GridPointSet #connected? when (x-1,y) pattern should return true