run FF
Failures:

  1) GridPoint #x
     Failure/Error: let(:y) { u }

     NameError:
       undefined local variable or method `u' for #<RSpec::ExampleGroups::GridPoint::X "example at ./spec/main_spec.rb:9">
     # ./spec/main_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/main_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/main_spec.rb:9:in `block (3 levels) in <top (required)>'

  2) GridPoint #y
     Failure/Error: let(:y) { u }

     NameError:
       undefined local variable or method `u' for #<RSpec::ExampleGroups::GridPoint::Y "example at ./spec/main_spec.rb:12">
     # ./spec/main_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/main_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/main_spec.rb:12:in `block (3 levels) in <top (required)>'

Finished in 0.00128 seconds (files took 0.04237 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/main_spec.rb:9 # GridPoint #x
rspec ./spec/main_spec.rb:12 # GridPoint #y