run ...........FF
Failures:

  1) GridPointSet #contain? when contains given grid_points contain should return true
     Failure/Error: expect(grid_point_set.contain?(grid_point1)).to eq true

     NameError:
       undefined local variable or method `v' for #<GridPointSet:0x0000000108894e38 @grid_points=[#<GridPoint:0x0000000108894ed8 @x=1, @y=2>, #<GridPoint:0x0000000108894e60 @x=3, @y=6>]>

             is_contain || v.same_coordinates_with?(target_grid_point)
                           ^
     # ./main.rb:38:in `block in contain?'
     # ./main.rb:37:in `each'
     # ./main.rb:37:in `reduce'
     # ./main.rb:37:in `contain?'
     # ./spec/main_spec.rb:68:in `block (4 levels) in <top (required)>'

  2) GridPointSet #contain? when doesn't contains given grid_points contain should return false
     Failure/Error: expect(grid_point_set.contain?(GridPoint.new(10, 20))).to eq false

     NameError:
       undefined local variable or method `v' for #<GridPointSet:0x000000010889e528 @grid_points=[#<GridPoint:0x000000010889e5c8 @x=1, @y=2>, #<GridPoint:0x000000010889e550 @x=3, @y=6>]>

             is_contain || v.same_coordinates_with?(target_grid_point)
                           ^
     # ./main.rb:38:in `block in contain?'
     # ./main.rb:37:in `each'
     # ./main.rb:37:in `reduce'
     # ./main.rb:37:in `contain?'
     # ./spec/main_spec.rb:73:in `block (4 levels) in <top (required)>'

Finished in 0.00205 seconds (files took 0.04294 seconds to load)
13 examples, 2 failures

Failed examples:

rspec ./spec/main_spec.rb:67 # GridPointSet #contain? when contains given grid_points contain should return true
rspec ./spec/main_spec.rb:72 # GridPointSet #contain? when doesn't contains given grid_points contain should return false