run ...FF
Failures:

  1) GridPoint #has_same_coordinates_with when two GridPoint object have same coordinates should return true
     Failure/Error: expect(obj.has_same_coordinates_with(GridPoint.new(x, y))).to eq true

     NoMethodError:
       undefined method `has_same_coordinates_with' for #<GridPoint:0x000000010817ef90 @x=4, @y=7>

               expect(obj.has_same_coordinates_with(GridPoint.new(x, y))).to eq true
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
     # ./spec/main_spec.rb:25:in `block (4 levels) in <top (required)>'

  2) GridPoint #has_same_coordinates_with when two GridPoint object have different coordinates should return true
     Failure/Error: expect(obj.has_same_coordinates_with(GridPoint.new(x+1, y+1))).to eq false

     NoMethodError:
       undefined method `has_same_coordinates_with' for #<GridPoint:0x000000010817c768 @x=4, @y=7>

               expect(obj.has_same_coordinates_with(GridPoint.new(x+1, y+1))).to eq false
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
     # ./spec/main_spec.rb:31:in `block (4 levels) in <top (required)>'

Finished in 0.00202 seconds (files took 0.0441 seconds to load)
5 examples, 2 failures

Failed examples:

rspec ./spec/main_spec.rb:24 # GridPoint #has_same_coordinates_with when two GridPoint object have same coordinates should return true
rspec ./spec/main_spec.rb:30 # GridPoint #has_same_coordinates_with when two GridPoint object have different coordinates should return true